### ISSUE TITLE
[Issue]: hip-5.7.1 failed tests: invalid device pointer Code 17 with  hipIpcOpenMemHandle( , , hipIpcMemLazyEnablePeerAccess)

### ISSUE THREAD

**Issue by littlewu2508** [ROCm-Developer-Tools/clr#46] opened 2024-01-18 01:15 UTC
### Problem Description

Running Gentoo hip tests on dual MI100 system result in two tests failure:

```
The following tests FAILED:                                                                                                                                                                                        
        1699 - Unit_hipIpcMemAccess_Semaphores (Timeout)                                                                                                                                                           
        1715 - Unit_hipIpcEventHandle_Functional (Timeout)
```

```
1699/1801 Testing: Unit_hipIpcMemAccess_Semaphores
1699/1801 Test: Unit_hipIpcMemAccess_Semaphores
Command: "/tmp/portage/dev-util/hip-5.7.1-r1/work/hip-tests-rocm-5.7.0/catch_build/catch_tests/multiproc/MultiProc" "Unit_hipIpcMemAccess_Semaphores"
Directory: /tmp/portage/dev-util/hip-5.7.1-r1/work/hip-tests-rocm-5.7.0/catch_build/catch_tests/multiproc
"Unit_hipIpcMemAccess_Semaphores" start time: Jan 18 01:15 CST
Output:
----------------------------------------------------------
Filters: Unit_hipIpcMemAccess_Semaphores

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
MultiProc is a Catch v2.13.4 host application.
Run with -? for options

-------------------------------------------------------------------------------
Unit_hipIpcMemAccess_Semaphores
-------------------------------------------------------------------------------
/tmp/portage/dev-util/hip-5.7.1-r1/work/hip-tests-rocm-5.7.0/catch/multiproc/hipIpcMemAccessTest.cc:80
...............................................................................

/tmp/portage/dev-util/hip-5.7.1-r1/work/hip-tests-rocm-5.7.0/catch/multiproc/hipIpcMemAccessTest.cc:152: FAILED:
  REQUIRE( false )
with message:
  Error: invalid device pointer
      Code: 17
      Str: hipIpcOpenMemHandle(reinterpret_cast<void **>(&B_d), shrd_mem->
  memHandle, hipIpcMemLazyEnablePeerAccess)
      In File: /tmp/portage/dev-util/hip-5.7.1-r1/work/hip-tests-rocm-5.7.0/
  catch/multiproc/hipIpcMemAccessTest.cc
      At line: 152

===============================================================================
test cases: 1 | 1 failed
assertions: 7 | 6 passed | 1 failed

<end of output>
```

### Operating System

Gentoo Prefix on upstream Linux kernel 6.1.69-1.1

### CPU

AMD EPYC 7702 64-Core Processor

### GPU

AMD Instinct MI100

### ROCm Version

ROCm 5.7.1

### ROCm Component

HIP

### Steps to Reproduce

In a fresh Gentoo Linux, with

`/etc/portage/package.accept_keywords`

```
*/* ~amd64
```

`/etc/portage/env/test.conf`
```
FEATURES="${FEATURES} test"
```

`/etc/portage/package.env/0-test`
```
dev-util/hip test.conf
```

And run `emerge --verbose hip`

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

```
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          NO

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD EPYC 7702 64-Core Processor    
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD EPYC 7702 64-Core Processor    
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2000                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            128                                
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    528222572(0x1f7c096c) KB           
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    528222572(0x1f7c096c) KB           
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    528222572(0x1f7c096c) KB           
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    AMD EPYC 7702 64-Core Processor    
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD EPYC 7702 64-Core Processor    
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2000                               
  BDFID:                   0                                  
  Internal Node ID:        1                                  
  Compute Unit:            128                                
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    528395328(0x1f7eac40) KB           
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    528395328(0x1f7eac40) KB           
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    528395328(0x1f7eac40) KB           
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 3                  
*******                  
  Name:                    gfx908                             
  Uuid:                    GPU-736edc556309c935               
  Marketing Name:          AMD Instinct MI100                 
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    2                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      8192(0x2000) KB                    
  Chip ID:                 29580(0x738c)                      
  ASIC Revision:           2(0x2)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1502                               
  BDFID:                   768                                
  Internal Node ID:        2                                  
  Compute Unit:            120                                
  SIMDs per CU:            4                                  
  Shader Engines:          8                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 64                                 
  SDMA engine uCode::      18                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    33538048(0x1ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS:                     
      Size:                    33538048(0x1ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx908:sramecc+:xnack-
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*******                  
Agent 4                  
*******                  
  Name:                    gfx908                             
  Uuid:                    GPU-4c8c97e3b14bcfdc               
  Marketing Name:          AMD Instinct MI100                 
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    3                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      8192(0x2000) KB                    
  Chip ID:                 29580(0x738c)                      
  ASIC Revision:           2(0x2)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1502                               
  BDFID:                   8960                               
  Internal Node ID:        3                                  
  Compute Unit:            120                                
  SIMDs per CU:            4                                  
  Shader Engines:          8                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 64                                 
  SDMA engine uCode::      18                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    33538048(0x1ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS:                     
      Size:                    33538048(0x1ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx908:sramecc+:xnack-
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***             
```

### Additional Information

The full build & test log

[build.log.gz](https://github.com/ROCm/clr/files/13970862/build.log.gz)

Test details:

[LastTest.log.gz](https://github.com/ROCm/clr/files/13970902/LastTest.log.gz)

**Comment by iassiour** [comment] 2024-01-21 16:12
Hi @littlewu2508 can you please rerun the failing tests with logging enabled e.g `export AMD_LOG_LEVEL=4` and paste the output.

**Comment by littlewu2508** [comment] 2024-01-22 03:39
> export AMD_LOG_LEVEL=4

[Unit_hipIpcMemAccess_Semaphores.log](https://github.com/ROCm/clr/files/14004425/Unit_hipIpcMemAccess_Semaphores.log)

**Comment by iassiour** [comment] 2024-01-22 13:28
I see this error in the logs from hipIpcGetMemHandle:
_Failed to create memory for IPC, failed with hsa_status: 4097_ 

Can you please confirm that the system has an up-to date version of the kernel mode driver (amdgpu-dkms) that should at least match rocm/5.7.1 release.

**Comment by littlewu2508** [comment] 2024-01-22 15:10
> I see this error in the logs from hipIpcGetMemHandle: _Failed to create memory for IPC, failed with hsa_status: 4097_
> 
> Can you please confirm that the system has an up-to date version of the kernel mode driver (amdgpu-dkms) that should at least match rocm/5.7.1 release.

The system uses the amdgpu driver from upstream Linux kernel, version 6.1.99. No amdgpu-dkms is installed.

**Comment by natshineman** [comment] 2024-06-18 22:08
Hello, was this issue ever resolved? I am seeing a similar issue on ROCM 6.0.0 with MI250X GPUs. 

Driver version is 6.3.6

**Comment by huanrwan-amd** [comment] 2024-09-25 20:29
@littlewu2508 and @natshineman Did you try with Ubuntu or other supported OS [https://rocm.docs.amd.com/en/docs-6.2.1/compatibility/compatibility-matrix.html](url) for the hip-test? amdgpu-dkms driver is a better support for these OS.

**Comment by Epliz** [comment] 2024-10-07 15:29
Hi @huanrwan-amd ,
I am also experiencing the same issue as described here, with very similar logs with ROCM 6.1.0 (OS: Ubuntu 22.04, 2x MI100 GPUs) while trying to share memory between two processes, each process using a separate GPU.
With ROCM 6.2.2, it actually fails at opening the memory with hipIPCOpenMemHandle.

What I have noticed though is that exporting pointers with hipMemPoolExportPointer seems to be working (I still need to confirm by seeing if my kernels using the shared points output the right thing, but hipMemcpyAsync seems to work transferring memory from one GPU to the other).
I used the code from [the docs](https://rocm.docs.amd.com/projects/HIP/en/latest/how-to/stream_ordered_allocator.html#device-pointer).

Looking at the implementation of hipIPCGetMemHandle and hipMemPoolExportPointer, they seem to be doing more or less the same thing, but a bit differently. I guess hipMemPoolExportPointer is the more correct one.

Fixing hipIPCGetMemHandle / hipIPCOpenMemHandle would be very much appreciated, as that's what people tend to use.

Best,
Epliz

**Comment by huanrwan-amd** [comment] 2024-10-07 20:00
@Epliz Thank you for your comments. 
Can you provide the code snippet that failing on hipIPCGetMemHandle / hipIPCOpenMemHandle and the driver info for you MI100? I can successfully call these APIs on MI300 with my testing code on ROCm6.2. 
Other comments from internal teams: The driver for AMD gpu has impacts on those API calls. It is suggested to use amdgpu-dkms drivers.

**Comment by Epliz** [comment] 2024-10-08 17:10
EDIT: the following code seems to work
~~Never mind, it doesn't seem to work with SOMA either...~~
Here is a small reproducer:
```
#include <hip/hip_runtime.h>

#include <stdint.h>
#include <stdio.h>

#include <string.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>

#define COMM_SOCKET_PATH "/tmp/comm_sock"

int main(int argc, char** argv) {

  int gpu_count;
  if (hipGetDeviceCount(&gpu_count) != hipSuccess) {
    return -1;
  }
  if (gpu_count < 2) {
    printf("this program needs two GPUs\n");
    return -1;
  }

  printf("Please run me twice\n!");

  int server_fd = -1; // socket to accept new connections, only one rank will have it
  int comm_socket = -1; // socket to do communications

  bool is_server;

  // try to become the server
  struct sockaddr_un server_addr;

  // Create a domain socket to sync processes
  int fd = socket(AF_UNIX, SOCK_STREAM, 0);
  if (fd == -1) {
    // error
    return - 1;
  }

  // Try bindnig socket to address
  memset(&server_addr, 0, sizeof(struct sockaddr_un));
  server_addr.sun_family = AF_UNIX;
  strncpy(server_addr.sun_path, COMM_SOCKET_PATH, sizeof(server_addr.sun_path) - 1);

  // we are the server if we managed to bind
  is_server = bind(fd, (struct sockaddr *)&server_addr, sizeof(struct sockaddr_un)) != -1;

  if (is_server) {
    printf("I am the server\n");
    // if we managed to bind, we should connect to all other ranks and they will be the socket
    // clients
    server_fd = fd;

    // Listen for connections
    if (listen(server_fd, 1) == -1) {
      return -1;
    }

    comm_socket = accept(server_fd, NULL, NULL);
    if (comm_socket == -1) {
      // error
      return -1;
    }
  } else {
    printf("I am a client\n");
    // if we didn't manage to bind, we are a mere client
    // we just need to connect to the server
    comm_socket = fd;

    if (connect(comm_socket, (struct sockaddr *)&server_addr, sizeof(struct sockaddr_un)) == -1) {
      // error
      return -1;
    }

    printf("connected to the server\n");
  }

  // we can already unlink as everyone has connected
  unlink(COMM_SOCKET_PATH);

  // the server gets gpu 0, the other one gpu 1
  int gpu = is_server ? 0 : 1;

  if (hipSetDevice(gpu) != hipSuccess) {
    return -1;
  }

  for (int d = 0; d < gpu_count; d++) {
    if (d == gpu) continue;
    if (hipDeviceEnablePeerAccess(d, 0) != hipSuccess) {
      // TODO: return error
      printf("Failed to enable peer to peer with %d\n", d);
      return -1;
    }
  }
  printf("Enabled peer to peer\n");

  // allocate some memory to share
  int* device_data;
  int* remote_device_data;

  // try to allocate 2MiB of data on the GPU (in case it needs to be big enough)
  if (hipMalloc(&device_data, sizeof(int) * 1024 * 1024 * 2) != hipSuccess) {
    return -1;
  }

  // now try to share the memory
  hipIpcMemHandle_t memHandle;
  if (hipIpcGetMemHandle(&memHandle, device_data) != hipSuccess) {
    // failed
    printf("Failed to get memory handle\n");
    return -1;
  }

  // send/receive the handles
  hipIpcMemHandle_t remoteMemHandle;
  if (is_server) {
    // send then receive
    if (write(comm_socket, &memHandle, sizeof(memHandle))< sizeof(memHandle)) {
      printf("interrupted write\n");
      return -1;
    }
    if (read(comm_socket, &remoteMemHandle, sizeof(memHandle)) < sizeof(memHandle)) {
      printf("interrupted read\n");
      return -1;
    }
  } else {
    // receive then send
    if (read(comm_socket, &remoteMemHandle, sizeof(memHandle)) < sizeof(memHandle)) {
      printf("interrupted read\n");
      return -1;
    }
    if (write(comm_socket, &memHandle, sizeof(memHandle))< sizeof(memHandle)) {
      printf("interrupted write\n");
      return -1;
    }
  }

  if (hipIpcOpenMemHandle((void**)&remote_device_data, remoteMemHandle, hipIpcMemLazyEnablePeerAccess) != hipSuccess) {
    // failed
    printf("Failed to open memory handle\n");
    return -1;
  }

  printf("Worked!\n");
  return 0;
}
```

Please run the program twice.

Best,
Epliz

**Comment by Epliz** [comment] 2024-10-08 17:15
EDIT: the following code seems to work
~~reproducer for issue with SOMA export/import of pointer:~~
```
#include <hip/hip_runtime.h>

#include <stdint.h>
#include <stdio.h>

#include <string.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>

#define COMM_SOCKET_PATH "/tmp/comm_sock"

int main(int argc, char** argv) {

  int gpu_count;
  if (hipGetDeviceCount(&gpu_count) != hipSuccess) {
    return -1;
  }
  if (gpu_count < 2) {
    printf("this program needs two GPUs\n");
    return -1;
  }

  printf("Please run me twice\n!");

  int server_fd = -1; // socket to accept new connections, only one rank will have it
  int comm_socket = -1; // socket to do communications

  bool is_server;

  // try to become the server
  struct sockaddr_un server_addr;

  // Create a domain socket to sync processes
  int fd = socket(AF_UNIX, SOCK_STREAM, 0);
  if (fd == -1) {
    // error
    return - 1;
  }

  // Try bindnig socket to address
  memset(&server_addr, 0, sizeof(struct sockaddr_un));
  server_addr.sun_family = AF_UNIX;
  strncpy(server_addr.sun_path, COMM_SOCKET_PATH, sizeof(server_addr.sun_path) - 1);

  // we are the server if we managed to bind
  is_server = bind(fd, (struct sockaddr *)&server_addr, sizeof(struct sockaddr_un)) != -1;

  if (is_server) {
    printf("I am the server\n");
    // if we managed to bind, we should connect to all other ranks and they will be the socket
    // clients
    server_fd = fd;

    // Listen for connections
    if (listen(server_fd, 1) == -1) {
      return -1;
    }

    comm_socket = accept(server_fd, NULL, NULL);
    if (comm_socket == -1) {
      // error
      return -1;
    }
  } else {
    printf("I am a client\n");
    // if we didn't manage to bind, we are a mere client
    // we just need to connect to the server
    comm_socket = fd;

    if (connect(comm_socket, (struct sockaddr *)&server_addr, sizeof(struct sockaddr_un)) == -1) {
      // error
      return -1;
    }

    printf("connected to the server\n");
  }

  // we can already unlink as everyone has connected
  unlink(COMM_SOCKET_PATH);

  // the server gets gpu 0, the other one gpu 1
  int gpu = is_server ? 0 : 1;
  int remote_gpu = is_server ? 1 : 0;

  if (hipSetDevice(gpu) != hipSuccess) {
    return -1;
  }

  for (int d = 0; d < gpu_count; d++) {
    if (d == gpu) continue;
    if (hipDeviceEnablePeerAccess(d, 0) != hipSuccess) {
      // TODO: return error
      printf("Failed to enable peer to peer with %d\n", d);
      return -1;
    }
  }
  printf("Enabled peer to peer\n");

  // allocate some memory to share
  int* device_data;
  int* remote_device_data;

  // try to allocate 2MiB of data on the GPU (in case it needs to be big enough)
  if (hipMalloc(&device_data, sizeof(int) * 1024 * 1024 * 2) != hipSuccess) {
    return -1;
  }

  // now try to share the memory
  hipMemPoolPtrExportData memHandle;
  if (hipMemPoolExportPointer(&memHandle, device_data) != hipSuccess) {
    // failed
    printf("Failed to export pointer\n");
    return -1;
  }


  // send/receive the handles
  hipMemPoolPtrExportData remoteMemHandle;
  if (is_server) {
    // send then receive
    if (write(comm_socket, &memHandle, sizeof(memHandle))< sizeof(memHandle)) {
      printf("interrupted write\n");
      return -1;
    }
    if (read(comm_socket, &remoteMemHandle, sizeof(memHandle)) < sizeof(memHandle)) {
      printf("interrupted read\n");
      return -1;
    }
  } else {
    // receive then send
    if (read(comm_socket, &remoteMemHandle, sizeof(memHandle)) < sizeof(memHandle)) {
      printf("interrupted read\n");
      return -1;
    }
    if (write(comm_socket, &memHandle, sizeof(memHandle))< sizeof(memHandle)) {
      printf("interrupted write\n");
      return -1;
    }
  }

  hipMemPoolProps poolProps = {};
  poolProps.allocType = hipMemAllocationTypePinned;
  poolProps.handleTypes = hipMemHandleTypePosixFileDescriptor;
  poolProps.location.type = hipMemLocationTypeDevice;
  poolProps.location.id = remote_gpu; // Assuming other device

  hipMemPool_t memPool;
  if (hipMemPoolCreate(&memPool, &poolProps) != hipSuccess) {
    return -1;
  }

  if (hipMemPoolImportPointer((void**)&remote_device_data, memPool, &remoteMemHandle) != hipSuccess) {
    // failed
    printf("Failed to import pointer\n");
    return -1;
  }

  printf("Worked!\n");
  return 0;
}
```

same thing, please run the program twice

**Comment by Epliz** [comment] 2024-10-08 17:37
It seems like the SOMA approach works in my more complex program (which I can't share), but not the reproducer

**Comment by huanrwan-amd** [comment] 2024-10-08 22:37
Hi @Epliz, thank you for posting your testing code. In your code:
`int comm_socket = accept(server_fd, NULL, NULL);` 
comm_socket is redeclared inside the loop, it will lose its value when running out of scope. Therefore, the write() and read() functions can not get the correct comm_socket value. You can just remove the declaration as:
`comm_socket = accept(server_fd, NULL, NULL);`

**Comment by Epliz** [comment] 2024-10-09 06:01
Hi @huanrwan-amd ,

Good catch! Actually it seems that after that fix both hip IPC and SOMA pointer export seem to work in the reproducer.
I will update the code snippets above just in case they are useful to someone.

I will try to see if there is a similar bug in my application, even though the bug here was just due to me trying to reduce my app (that part was correct there).

Best,
Epliz

**Comment by huanrwan-amd** [comment] 2024-10-09 13:49
Hi @Epliz, Thanks for the confirmation. Great to see it works on your side with MI100.

**Comment by huanrwan-amd** [comment] 2024-10-11 20:58
@littlewu2508 and @natshineman , closed the issue for no updates for 2 weeks. If you would like us to investigate further, please leave comments.

**Closed as not planned by huanrwan-amd** 2024-10-11 20:58 UTC
Labels: Under Investigation
